# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyfs',
            name='eyfs_training_declare',
        ),
        migrations.RemoveField(
            model_name='eyfs',
            name='eyfs_understand',
        ),
        migrations.RemoveField(
            model_name='eyfs',
            name='share_info_declare',
        ),
        migrations.AddField(
            model_name='arc',
            name='eyfs_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eyfs',
            name='eyfs_course_date_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyfs',
            name='eyfs_course_date_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyfs',
            name='eyfs_course_date_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eyfs',
            name='eyfs_course_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
