# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='childcare_type_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FURTHER_INFORMATION', 'FURTHER_INFORMATION')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='criminal_record_check_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FURTHER_INFORMATION', 'FURTHER_INFORMATION')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='declarations_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FURTHER_INFORMATION', 'FURTHER_INFORMATION')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='eyfs_training_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FURTHER_INFORMATION', 'FURTHER_INFORMATION')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_aid_training_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FURTHER_INFORMATION', 'FURTHER_INFORMATION')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='health_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FURTHER_INFORMATION', 'FURTHER_INFORMATION')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='login_details_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FURTHER_INFORMATION', 'FURTHER_INFORMATION')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='people_in_home_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FURTHER_INFORMATION', 'FURTHER_INFORMATION')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='personal_details_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FURTHER_INFORMATION', 'FURTHER_INFORMATION')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='references_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FURTHER_INFORMATION', 'FURTHER_INFORMATION')], max_length=50),
        ),
    ]
