# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-15 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='display_contact_details_on_web',
            field=models.NullBooleanField(default=None),
        ),
    ]
