# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180509_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='background_check_declare',
        ),
        migrations.RemoveField(
            model_name='application',
            name='inspect_home_declare',
        ),
        migrations.RemoveField(
            model_name='application',
            name='interview_declare',
        ),
        migrations.AddField(
            model_name='application',
            name='childcare_type_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='criminal_record_check_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='eyfs_training_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='first_aid_training_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='health_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='login_details_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='people_in_home_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='personal_details_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='references_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='childcare_type_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='criminal_record_check_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='declarations_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='eyfs_training_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_aid_training_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='health_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='login_details_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='people_in_home_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='personal_details_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='references_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='childcare_type_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='dbs_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='eyfs_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='first_aid_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='health_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='login_details_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='people_in_home_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='personal_details_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='references_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
    ]
