# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-04 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_adultinhome_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultinhome',
            name='health_check_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
