# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180509_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckCurrent',
            fields=[
                ('illness_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('current_illness', models.BooleanField()),
            ],
            options={
                'db_table': 'CURRENT_ILLNESS',
            },
        ),
        migrations.CreateModel(
            name='HealthCheckHospital',
            fields=[
                ('illness_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'HOSPITAL_ADMISSION',
                'ordering': ['start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthCheckSerious',
            fields=[
                ('illness_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('serious_illness', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'SERIOUS_ILLNESS',
                'ordering': ['start_date'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arc',
            name='eyfs_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], max_length=50),
        ),
        migrations.AddField(
            model_name='healthcheckserious',
            name='person_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='application.AdultInHome'),
        ),
        migrations.AddField(
            model_name='healthcheckhospital',
            name='person_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='application.AdultInHome'),
        ),
        migrations.AddField(
            model_name='healthcheckcurrent',
            name='person_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='application.AdultInHome'),
        ),
    ]
