# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20180511_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcheckserious',
            name='serious_illness',
        ),
    ]
