# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180509_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminalrecordcheck',
            name='send_certificate_declare',
        ),
    ]
