# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_adultinhome_health_check_status'),
        ('application', '0002_auto_20180509_1412'),
    ]

    operations = [
    ]
