# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_merge_20180511_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultinhome',
            name='email_resent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arc',
            name='childcare_type_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='dbs_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='eyfs_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='first_aid_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='health_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='login_details_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='people_in_home_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='personal_details_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='references_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
    ]
