# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20180511_1126'),
        ('application', '0004_remove_criminalrecordcheck_send_certificate_declare'),
    ]

    operations = [
    ]
