# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20180514_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultinhome',
            name='email_resent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adultinhome',
            name='email_resent',
            field=models.IntegerField(default=0),
        ),
    ]
