# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_merge_20180514_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='suitable_declare',
            field=models.NullBooleanField(default=None),
        ),
    ]
