# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_merge_20180514_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='security_question',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sms_resend_attempts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
