# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20180517_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='sms_resend_attempts_expiry_date',
            field=models.IntegerField(default=0, blank=True, null=True),
        ),
    ]
