# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_adultinhome_current_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcheckcurrent',
            name='current_illness',
        ),
    ]
