# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_remove_healthcheckcurrent_current_illness'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultinhome',
            name='health_check_complete',
            field=models.BooleanField(default=False),
        ),
    ]
