# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_adultinhome_health_check_complete'),
        ('application', '0004_remove_criminalrecordcheck_send_certificate_declare'),
    ]

    operations = [
    ]
