# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_merge_20180514_1633'),
        ('application', '0006_auto_20180514_1005'),
        ('application', '0010_merge_20180515_0851'),
    ]

    operations = [
    ]
