# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_merge_20180515_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adultinhome',
            name='health_check_complete',
        ),
        migrations.RemoveField(
            model_name='adultinhome',
            name='permission_declare',
        ),
        migrations.AlterField(
            model_name='adultinhome',
            name='email',
            field=models.CharField(null=True, blank=True, default=None, max_length=100),
            preserve_default=False,
        ),
    ]
