# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20180515_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultinhome',
            name='health_check_status',
            field=models.CharField(default='To do', max_length=50),
        ),
    ]
