# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-21 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20180515_1047'),
        ('application', '0007_merge_20180518_1141'),
    ]

    operations = [
    ]
