# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20180309_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='eyfs_questions_declare',
        ),
        migrations.AddField(
            model_name='application',
            name='share_info_declare',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='applicanthomeaddress',
            name='childcare_address',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='applicanthomeaddress',
            name='current_address',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='adults_in_home',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='background_check_declare',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='children_in_home',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='children_turning_16',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='information_correct_declare',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='inspect_home_declare',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='interview_declare',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='eyfs',
            name='eyfs_questions_declare',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='eyfs',
            name='eyfs_training_declare',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='eyfs',
            name='eyfs_understand',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='firstaidtraining',
            name='renew_certificate',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='firstaidtraining',
            name='show_certificate',
            field=models.NullBooleanField(default=None),
        ),
    ]
