# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20180309_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='eyfs_questions_declare',
            new_name='change_declare',
        ),
        migrations.RenameField(
            model_name='eyfs',
            old_name='eyfs_questions_declare',
            new_name='share_info_declare',
        ),
        migrations.AddField(
            model_name='application',
            name='share_info_declare',
            field=models.NullBooleanField(),
        ),
    ]
