# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20180309_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='eyfs_questions_declare',
            new_name='share_info_declare',
        ),
    ]
