# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20180315_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eyfs',
            old_name='eyfs_questions_declare',
            new_name='share_info_declare',
        ),
    ]
