# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20180314_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='change_declare',
            field=models.NullBooleanField(),
        ),
    ]
