# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_application_change_declare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='share_info_declare',
            field=models.NullBooleanField(default=None),
        ),
    ]
