# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-01 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_application_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ofsted_visit_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
