# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-31 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20180727_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='arc',
            name='childcare_address_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AddField(
            model_name='arc',
            name='childcare_training_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AddField(
            model_name='arc',
            name='insurance_cover_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
    ]
