# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-16 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_auto_20180816_1003'),
        ('application', '0022_adultinhome_healthcheckstatus_update'),
    ]

    operations = [
    ]
