# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_merge_20180816_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalrecordcheck',
            name='capita',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='criminalrecordcheck',
            name='lived_abroad',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='criminalrecordcheck',
            name='military_base',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='criminalrecordcheck',
            name='on_update',
            field=models.NullBooleanField(),
        ),
    ]
