# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-24 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20180824_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EYFS',
            new_name='ChildcareTraining',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='eyfs_training_arc_flagged',
            new_name='childcare_training_arc_flagged',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='eyfs_training_status',
            new_name='childcare_training_status',
        ),
    ]
