# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-24 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_auto_20180824_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arc',
            name='childcare_training_review',
        ),
    ]
