# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-24 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_auto_20180824_1447'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='childcaretraining',
            table='CHILDCARE_TRAINING',
        ),
    ]
