# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-30 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_application_publish_details'),
        ('application', '0029_auto_20180824_1549'),
    ]

    operations = [
    ]
