# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-29 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20180823_0947'),
        ('application', '0029_auto_20180824_1549'),
    ]

    operations = [
    ]
