# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-29 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_merge_20180829_1421'),
        ('application', '0026_auto_20180828_0938'),
    ]

    operations = [
    ]
