# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-31 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_merge_20180830_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='change_declare',
            new_name='declaration_confirmation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='display_contact_details_on_web',
        ),
        migrations.RemoveField(
            model_name='application',
            name='information_correct_declare',
        ),
        migrations.RemoveField(
            model_name='application',
            name='share_info_declare',
        ),
        migrations.RemoveField(
            model_name='application',
            name='suitable_declare',
        ),
    ]
