# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-03 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_auto_20180831_0926'),
        ('application', '0026_auto_20180828_0938'),
    ]

    operations = [
    ]
