# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-06 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_merge_20180903_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='working_in_other_childminder_home',
            field=models.BooleanField(default=False),
        ),
    ]
