# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-14 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_auto_20180911_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('child', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_names', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('birth_day', models.IntegerField(blank=True)),
                ('birth_month', models.IntegerField(blank=True)),
                ('birth_year', models.IntegerField(blank=True)),
                ('lives_with_childminder', models.NullBooleanField()),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
            options={
                'db_table': 'CHILD',
            },
        ),
        migrations.CreateModel(
            name='ChildAddress',
            fields=[
                ('child_address_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('child', models.IntegerField(blank=True, null=True)),
                ('street_line1', models.CharField(blank=True, max_length=100)),
                ('street_line2', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=8)),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
            options={
                'db_table': 'CHILD_ADDRESS',
            },
        ),
    ]
