# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-14 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_auto_20180911_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='arc',
            name='your_children_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
    ]
