# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-18 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0033_auto_20180906_1606'),
        ('application', '0038_arc_your_children_review'),
    ]

    operations = [
    ]
