# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-21 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0040_child_childaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arccomments',
            name='field_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
