# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-26 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_auto_20180921_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
