# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-26 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_auto_20180921_1314'),
        ('application', '0041_application_own_children_not_in_home'),
    ]

    operations = [
    ]
