# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-27 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_merge_20180926_1015'),
        ('application', '0042_application_date_last_accessed'),
    ]

    operations = [
    ]
