# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-03 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_merge_20180927_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='publish_details',
        ),
    ]
