# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-23 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_remove_application_publish_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultinhome',
            name='children_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='known_to_council',
            field=models.NullBooleanField(),
        ),
    ]
