# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-26 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0045_application_publish_details'),
        ('application', '0045_auto_20181023_1536'),
    ]

    operations = [
    ]
