# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-14 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_merge_20181026_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='change_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adultinhome',
            name='children_details',
            field=models.TextField(default='', null=True),
        ),
    ]
