# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_merge_20181026_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultinhome',
            name='children_details',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='previousaddress',
            name='postcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
