# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-15 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0047_auto_20181114_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='change_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
