# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-19 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_auto_20181115_1611'),
        ('application', '0047_auto_20181115_0950'),
    ]

    operations = [
    ]
