# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-01 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0049_merge_20181119_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalrecordcheck',
            name='enhanced_check',
            field=models.NullBooleanField(),
        ),
    ]
