# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-21 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0049_merge_20181119_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reasons_known_to_social_services',
            field=models.TextField(null=True),
        ),
    ]
