# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0050_adultinhome_cygnum_relationship_to_childminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='childinhome',
            name='cygnum_relationship_to_childminder',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
