# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-05 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0050_criminalrecordcheck_enhanced_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adultinhome',
            name='children_details',
        ),
        migrations.RemoveField(
            model_name='application',
            name='own_children_not_in_home',
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='reasons_known_to_council_health_check',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='known_to_social_services_pith',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='application',
            name='reasons_known_to_social_services',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='reasons_known_to_social_services_pith',
            field=models.TextField(default='', null=True),
        ),
    ]
