# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-04 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0051_auto_20190204_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adultinhome',
            old_name='children_details',
            new_name='reasons_known_to_council_health_check',
        ),
    ]
