# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-11 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0052_auto_20190207_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalrecordcheck',
            name='certificate_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='criminalrecordcheck',
            name='within_three_months',
            field=models.NullBooleanField(),
        ),
    ]
