# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-05 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0052_auto_20190204_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='own_children_not_in_home',
            new_name='known_to_social_services_pith',
        ),
    ]
