# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-13 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0053_auto_20190213_1635'),
        ('application', '0053_auto_20190211_1109'),
    ]

    operations = [
    ]
