# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-14 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0053_auto_20190211_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitaDBSFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('date_uploaded', models.DateField()),
            ],
            options={
                'db_table': 'CAPITA_DBS_FILE',
            },
        ),
    ]
