# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-13 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0054_merge_20190213_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultinhome',
            name='certificate_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='enhanced_check',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='within_three_months',
            field=models.NullBooleanField(),
        ),
    ]
