# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-15 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0055_auto_20190213_1702'),
        ('application', '0054_capitadbsfile'),
    ]

    operations = [
    ]
