# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-03 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0057_adultinhome_cygnum_relationship_to_childminder'),
        ('application', '0057_application_application_expiry_email_sent'),
    ]

    operations = [
    ]
