# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-07 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0057_adultinhome_cygnum_relationship_to_childminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationReference',
        ),
    ]
