# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-03 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0058_merge_20190903_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationReference',
        ),
        migrations.RemoveField(
            model_name='applicanthomeaddress',
            name='move_in_month',
        ),
        migrations.RemoveField(
            model_name='applicanthomeaddress',
            name='move_in_year',
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='name_end_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='name_end_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='name_end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='name_start_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='name_start_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='name_start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantname',
            name='end_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantname',
            name='end_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantname',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantname',
            name='start_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantname',
            name='start_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantname',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='moved_in_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='moved_in_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='moved_in_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='moved_out_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='moved_out_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='moved_out_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arc',
            name='adult_update_review',
            field=models.CharField(blank=True, choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='moved_in_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='moved_in_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='moved_in_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='moved_out_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='moved_out_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='moved_out_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previousname',
            name='end_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previousname',
            name='end_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previousname',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previousname',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previousname',
            name='start_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previousname',
            name='start_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previousname',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
