# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0059_auto_20190311_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousname',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
