# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-16 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0060_applicantname_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantname',
            name='other_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
