# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0061_auto_20190318_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_expiry_email_sent',
            field=models.NullBooleanField(),
        ),
    ]
