# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-16 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0061_applicantname_other_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultinhome',
            name='other_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='other_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
