# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0062_application_application_expiry_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_expiry_email_sent',
            field=models.NullBooleanField(default=False),
        ),
    ]
