# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0062_auto_20190325_1303'),
        ('application', '0063_auto_20190325_1450'),
    ]

    operations = [
    ]
