# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-15 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0064_reference_other_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='CCR',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='EYC',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='VCR',
            field=models.NullBooleanField(default=False),
        ),
    ]
