# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-17 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0064_reference_other_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultinhome',
            name='PITH_mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
