# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0064_merge_20190326_0953'),
        ('application', '0064_merge_20190327_1030'),
    ]

    operations = [
    ]
