# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0065_merge_20190328_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='arc',
            name='adult_update_review',
            field=models.CharField(blank=True, choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50, null=True),
        ),
    ]
