# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-29 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0065_adultinhome_pith_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultInHomeAddress',
            fields=[
                ('adult_in_home_address_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('adult_in_home_address', models.IntegerField(blank=True)),
                ('street_line1', models.CharField(blank=True, max_length=100)),
                ('street_line2', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=8)),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
            options={
                'db_table': 'ADULT_IN_HOME_ADDRESS',
            },
        ),
    ]
