# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-28 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0065_adultinhome_pith_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultinhome',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='postcode',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='street_line1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='street_line2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='town',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
