# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-16 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0065_adultinhome_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adultinhome',
            old_name='mobile_number',
            new_name='PITH_mobile_number',
        ),
    ]
