# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-11 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0066_auto_20191104_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultinhome',
            name='PITH_same_address',
            field=models.NullBooleanField(),
        ),
    ]
