# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-14 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0067_auto_20191111_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcaretype',
            name='childcare_places',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childcaretype',
            name='weekday_after_school',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='childcaretype',
            name='weekday_all_day',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='childcaretype',
            name='weekday_am',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='childcaretype',
            name='weekday_before_school',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='childcaretype',
            name='weekday_pm',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='childcaretype',
            name='weekend_all_day',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='childcaretype',
            name='weekend_am',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='childcaretype',
            name='weekend_pm',
            field=models.NullBooleanField(),
        ),
    ]
