# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-31 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0067_adultinhome_pith_same_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultinhome',
            name='PITH_same_address',
            field=models.NullBooleanField(default=True),
        ),
    ]
