# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-13 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0067_auto_20191111_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildcareTiming',
            fields=[
                ('childcare_timing_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('weekday_before_school', models.BooleanField()),
                ('weekday_after_school', models.BooleanField()),
                ('weekday_am', models.BooleanField()),
                ('weekday_pm', models.BooleanField()),
                ('weekday_all_day', models.BooleanField()),
                ('weekend_am', models.BooleanField()),
                ('weekend_pm', models.BooleanField()),
                ('weekend_all_day', models.BooleanField()),
            ],
            options={
                'db_table': 'CHILDCARE_TIMING',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='childcare_timing_status',
            field=models.CharField(blank=True, choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], max_length=50),
        ),
        migrations.AddField(
            model_name='childcaretiming',
            name='application_id',
            field=models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='application.Application'),
        ),
    ]
