# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-13 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0068_auto_20191113_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcaretiming',
            name='weekday_after_school',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='childcaretiming',
            name='weekday_all_day',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='childcaretiming',
            name='weekday_am',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='childcaretiming',
            name='weekday_before_school',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='childcaretiming',
            name='weekday_pm',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='childcaretiming',
            name='weekend_all_day',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='childcaretiming',
            name='weekend_am',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='childcaretiming',
            name='weekend_pm',
            field=models.NullBooleanField(),
        ),
    ]
