# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0068_auto_20191115_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultinhomeaddress',
            name='moved_in_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adultinhomeaddress',
            name='moved_in_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adultinhomeaddress',
            name='moved_in_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
